<div class="search-panel">
	<h2><?php echo $this->T('location-on-map');?></h2>
	<div id="googlemap" style="width: 100%; height: 400px;"></div>
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&language=uk"></script>
	<script type="text/javascript">
	  function initialize() {
	    var latlng = new google.maps.LatLng(<?php echo $this->lat ?>, <?php echo $this->lng ?>);
	    var myOptions = {
	      zoom: 16,
	      center: latlng,
	      disableDefaultUI: true,
	      mapTypeId: google.maps.MapTypeId.ROADMAP
	    };
	    // create map
	    var map = new google.maps.Map(document.getElementById("googlemap"), myOptions);
	    // add marker
	    var marker = new google.maps.Marker({
	        position: latlng,
	        map: map, 
	        title:"<?php echo $this->label ?>",
	        icon: "/images/report-logo.png"
	    });
	  }
	  $(document).ready(function () {
		  initialize();
	  });
	  
	</script>

</div>