<?php 

// get locale to use for interface
$loc = $this->getLocale();

$this->setBreadcrumbs(array(
	'Головна' => '/',
	'Проблеми міста ' . $this->cityTitle => $this->url(array('city' => $this->citySeoTitle) ,'city'),
	$this->problem->msg => ''
));

?>
<h1><?php echo $this->problem->msg ?></h1>

<p><?php echo $this->problem->address ?></p>

<img alt="<?php echo $this->problem->msg ?>" src="/images/problem/<?php echo $this->problem->photo ?>" />

<h2 class="comments">Залиште свій коментар</h2>

<div id="vk_comments"></div>
<script type="text/javascript">
VK.Widgets.Comments("vk_comments", {limit: 10, width: "496", attach: "photo"});
</script>

<p>ПРИМІТКА: маєте можливість прикріпити фото даної проблеми зроблене з іншого ракурсу,<br />
для цього натисніть посилання "прикріпити" розташоване зправа під вашим зображенням.</p>