<?php 

// load custom title
$this->headTitle($this->problem->msg);

$this->headMeta()
	->setName('description', $this->T('meta-description'))
	->setName('keywords', $this->T('meta-keywords'));

// get locale to use for interface
$loc = $this->getLocale();

$this->setBreadcrumbs(array(
	'Головна' => '/',
	'Проблеми міста ' . $this->cityTitle => $this->url(array('city' => $this->citySeoTitle) ,'city'),
	$this->problem->msg => ''
));

$this->addPanel($this->partial('panel-social-share.phtml'));

?>
<h1><?php echo $this->problem->msg ?></h1>

<img alt="<?php echo $this->problem->msg ?>" src="/images/problem/<?php echo $this->problem->photo ?>" />

<h2 class="comments">Залиште свій коментар</h2>

<div id="vk_comments"></div>
<script type="text/javascript">
VK.Widgets.Comments("vk_comments", {limit: 10, width: "496", attach: "photo"});
</script>

<p>ПРИМІТКА. У вас є можливість прикріпити фото даної проблеми, зроблене з іншого ракурсу.<br />
Для цього натисніть посилання "Прикріпити" перед тим, як надіслати коментар.</p>