<?php 

// load custom title
$this->headTitle($this->problem->msg);

$this->headMeta()
	->setName('description', $this->T('meta-description'))
	->setName('keywords', $this->T('meta-keywords'));

// get locale to use for interface
$loc = $this->getLocale();

$this->setBreadcrumbs(array(
	'Головна' => '/',
	'Проблеми міста ' . $this->cityTitle => $this->url(array('city' => $this->citySeoTitle) ,'city'),
	$this->problem->msg => ''
));

$this->addPanel($this->partial('panel-social-share.phtml'));

?>
<h1><?php echo $this->problem->msg ?></h1>

<img alt="<?php echo $this->problem->msg ?>" src="/images/problem/<?php echo $this->problem->photo ?>" />

