<?php 
$this->addPanel($this->partial('panel-social-share.phtml'));
?>

<h1>Програма для мобільного</h1>

<p>
Програма для мобільного полегшує збір та накопичення інформації на сайті.
Ваш мобільний завжди з вами і для того щоб надіслати інформацію на сайт -  
достатньо лише побачити проблему, витягнути мобільник з кишені, запустити програму та створити 
звіт.
</p>

<p>Програма для мобільного побудована таким чином, що не потребує постійного підключення до Інтернету.
Всі звіти будуть збережені в пам’яті телефону і можуть бути завантажені на веб-сайт 
коли Вам буде зручно, наприклад вдома з використанням <b>WiFi</b> чи мережі <b>3G</b>.</p>

<p>
На даний час вже готова програма під мобільну платформу <b>Android</b>.
Залиште будь-ласка відгук під яку ще мобільну платформу ви хотіли б отримати програму.
</p>

<h1>Програма для Android</h1>

<div style="float:right; width: 300px;">

Також можна використати QR код 

<a href="https://market.android.com/details?id=ua.org.vladu.povidom"><img border="0" src="/images/qr-code-for-app.png" alt="Програма для мобільного Android" /></a>

 
</div>

<div>

<p>Завантажте програму на сторінці <a href="https://market.android.com/details?id=ua.org.vladu.povidom">Повідом Владу на Android Market</a>
<br />або клацнувши зображення
<br />
<a href="https://market.android.com/details?id=ua.org.vladu.povidom"><img alt="Повідом Владу на Android Market" src="/images/android-logo-white.png" border="0" /></a>

</p>
</div>


<p>
Запрошуємо програмістів та ентузіастів до розробки програм-клієнтів для:
<ul>
<li>iPhone</li>
<li>Windows Phone 7</li>
<li>Symbian</li>
</ul>
</p>