<?php 

$this->addPanel('<div class="search-panel"> 
<h1>Про мобільну програму</h1>

<p>
Твій мобільник завжди з тобою, тож достатньо запустити програму та відразу створити звіт, 
коли бачиш звалище сміття, розбитий ліхтар чи пошкоджений асвальт.
</p>

<p>Програма не потребує постійного підключення до Інтернету.
Усі звіти будуть збережені в пам’яті телефону та їх можна надіслати пізніше,
 наприклад через <b>WiFi</b> або мережу <b>3G</b>.</p>
</div>');

$this->addPanel($this->partial('panel-social-share.phtml'));
?>

<h1>Програма для Android</h1>

<div style="float:right; width: 300px;position: relative; top:-30px; left:-100px;">
<a href="https://market.android.com/details?id=ua.org.vladu.povidom"><img border="0" src="/images/qr-code-for-app.png" alt="Програма для мобільного Android" /></a>
</div>



<div>
<a href="https://market.android.com/details?id=ua.org.vladu.povidom"><img alt="Повідом Владу на Android Market" src="/images/android-logo-white.png" border="0" /></a>
</div>

<h1><b>iPhone</b>, <b>Windows Phone 7</b> та інші платформи з’являться незабаром...</h1>
<p>УВАГА! Зв’яжіться з нами, якщо хочете взяти участь у розробці програм для мобільних телефонів.</p>