<?php 

$this->addPanel('<div class="search-panel"> 
<h1>Про мобільну програму</h1>

<p>
Твій мобільник завжди з тобою, тож достатньо запустити програму та відразу створити звіт, 
коли бачиш звалище сміття, розбитий ліхтар чи пошкоджений асфальт.
</p>

<p>Програма не потребує постійного підключення до Інтернету.
Усі звіти зберігаються в пам’яті телефону та їх можна надіслати пізніше,
 наприклад через <b>WiFi</b> або мережу <b>3G</b>.</p>
</div>');

$this->addPanel($this->partial('panel-social-share.phtml'));

?>
<br><br>
<div style="float:left;width: 99%;text-align: center;">
<a href="https://market.android.com/details?id=ua.org.vladu.povidom"><img alt="Повідом Владу на Android Market" src="/images/android-logo-white.png" border="0" /></a>
</div>
<br><br>
<div style="float:left; width: 300px;display:none;">
<a href="https://market.android.com/details?id=ua.org.vladu.povidom"><img border="0" src="/images/qr-code-for-app.png" alt="Програма для мобільного Android" /></a>
</div>
<h2 style="text-align:center;width:99%;"><br><br><br><br><br>програми під <b>iPhone</b>, <b>Windows Phone 7</b> та інші платформи з’являться незабаром...
<br>
<br><br><br></h2>